
# NumPy exercises


In [ ]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5




## Array creation

### Create a numpy array of size 10, filled with zeros.

In [ ]:
# your code goes here
np.zeros(10,dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)



### Create a numpy array with values ranging from 10 to 49

In [ ]:
# your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])



### Create a numpy matrix of 2*2 integers, filled with ones.

In [ ]:
# your code goes here
a=np.ones((2,2),dtype=np.int16)

In [ ]:
a.astype(np.float)

array([[1., 1.],
       [1., 1.]])



### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [ ]:
# your code goes here
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [ ]:
# your code goes here
X= np.array([[1,2,3],[4,5,6]])
np.ones_like(X,1)

array([[1, 1, 1],
       [1, 1, 1]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [ ]:
# your code goes here
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])



### Create a numpy matrix of 4*4 integers, filled with fives.

In [ ]:
# your code goes here
X = np.array([[1,2,3,4],[1]*4,[1]*4,[1]*4])
np.full_like(X,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [ ]:
# your code goes here




### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [ ]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [ ]:
# your code goes here




### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [ ]:
# your code goes here
np.random.rand(3,3,3)

array([[[0.2662106 , 0.68735189, 0.42075184],
        [0.32645711, 0.31357845, 0.48118824],
        [0.70133907, 0.25492754, 0.20782725]],

       [[0.39330749, 0.34943331, 0.13551677],
        [0.84496062, 0.68099636, 0.99089261],
        [0.8404223 , 0.52844414, 0.53113323]],

       [[0.72274509, 0.71483974, 0.15372139],
        [0.95053312, 0.02168542, 0.39770033],
        [0.83831267, 0.82189747, 0.62315014]]])



### Given the X python list convert it to an Y numpy array

In [ ]:
# your code goes here
X = [1,2,3,4]

Y = np.array(X)

Y

array([1, 2, 3, 4])



### Given the X numpy array, make a copy and store it on Y.

In [ ]:
# your code goes here

X=np.copy(Y)

print(X,id(X))

print(Y,id(Y))

[1 2 3 4] 140162490182352
[1 2 3 4] 140162491743008




### Create a numpy array with numbers from 1 to 10

In [ ]:
# your code goes here
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



### Create a numpy array with the odd numbers between 1 to 10

In [ ]:
# your code goes here
np.arange(1,11,2)

array([1, 3, 5, 7, 9])



### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [ ]:
# your code goes here
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



### Show the memory size of the given Z numpy matrix

In [ ]:
# your code goes here
x = np.array([1,2,3,4])

print("the size of x is :",x.itemsize * x.size)

the size of x is : 32



## Array indexation


### Given the X numpy array, show it's first element

In [ ]:
# your code goes here
X[0] 

1



### Given the X numpy array, show it's last element

In [ ]:
# your code goes here
X[-1]

4



### Given the X numpy array, show it's first three elements

In [ ]:
# your code goes here
X = np.array([1,2,3,4,5,6,7,9,10])

X[:3]

array([1, 2, 3])



### Create a numpy array with numbers from 1 to 10, in descending order.

In [ ]:
# your code goes here
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])



### Given the X numpy array, show all middle elements

In [ ]:
# your code goes here
X = np.array([1,2,3,4,5])

X[1:-1]

array([2, 3, 4])



### Given the X numpy array, show the elements in reverse position

In [ ]:
# your code goes here
X[::-1]

array([5, 4, 3, 2, 1])



### Given the X numpy array, show the elements in an odd position

In [ ]:
# your code goes here
X[1::2]

array([2, 4])



### Given the X numpy matrix, show the first row elements

In [ ]:
# your code goes here
X = np.random.randint(low=1,high=11,size=(4,5))
print(X)

X[0]


[[ 3 10  7  6  9]
 [ 6  6  1  9  2]
 [10  9  4  9  1]
 [10  6  5  9  1]]


array([ 3, 10,  7,  6,  9])



### Given the X numpy matrix, show the last row elements

In [ ]:
# your code goes here
X[-1]

array([9, 2, 5, 6, 9])



### Given the X numpy matrix, show the first element on first row

In [ ]:
# your code goes here
X[0,0]

1



### Given the X numpy matrix, show the last element on last row

In [ ]:
# your code goes here
X[-1,-1]

9



### Given the X numpy matrix, show the middle row elements

In [ ]:
# your code goes here
rows=X.shape[0]
X[int(rows/2) ] if rows%2!=0 else X[int(rows/2):int(rows/2)+1]

array([[9, 5, 5, 9, 5]])



### Given the X numpy matrix, show the first two elements on the first two rows

In [ ]:
# your code goes here
print(X)
X[:2,:2]

[[ 2  7 10  8  7]
 [ 4  8  4  1  3]
 [ 9  5  5  9  5]
 [ 9  5 10  1  4]]


array([[2, 7],
       [4, 8]])



### Given the X numpy matrix, show the last two elements on the last two rows

In [ ]:
# your code goes here
print(X)
X[-2:,-2:]

[[ 2  7 10  8  7]
 [ 4  8  4  1  3]
 [ 9  5  5  9  5]
 [ 9  5 10  1  4]]


array([[9, 5],
       [1, 4]])


## Array manipulation


### Convert the given integer numpy array to float

In [ ]:
# your code goes here
X.astype(np.float)

array([[ 2.,  7., 10.,  8.,  7.],
       [ 4.,  8.,  4.,  1.,  3.],
       [ 9.,  5.,  5.,  9.,  5.],
       [ 9.,  5., 10.,  1.,  4.]])



### Reverse the given numpy array (first element becomes last)

In [ ]:
# your code goes here
print(X)
X[::-1]

[[ 2  7 10  8  7]
 [ 4  8  4  1  3]
 [ 9  5  5  9  5]
 [ 9  5 10  1  4]]


array([[ 9,  5, 10,  1,  4],
       [ 9,  5,  5,  9,  5],
       [ 4,  8,  4,  1,  3],
       [ 2,  7, 10,  8,  7]])



### Order (sort) the given numpy array

In [ ]:
# your code goes here
X =np.array([[ 2 , 7, 10,  8,  7],
             [ 4  ,8  ,4  ,1 , 3],
             [ 9  ,5 , 5,  9,  5],
             [ 9  ,5 ,10  ,1 , 4],
             [ -1  ,5 ,10  ,1 , 4]] ) 

Y =np.array([[2,3],
      [1,5]])
Y.sort()

Y

array([[2, 3],
       [1, 5]])



### Given the X numpy array, set the fifth element equal to 1

In [ ]:
# your code goes here

X[4]=1
X

array([[ 2,  7, 10,  8,  7],
       [ 4,  8,  4,  1,  3],
       [ 9,  5,  5,  9,  5],
       [ 9,  5, 10,  1,  4],
       [ 1,  1,  1,  1,  1]])



### Given the X numpy array, change the 50 with a 40

In [ ]:
# your code goes here
mask = X==5

X[mask]=-1

In [ ]:
X

array([[ 2,  7, 10,  8,  7],
       [ 4,  8,  4,  1,  3],
       [ 9, -1, -1,  9, -1],
       [ 9, -1, 10,  1,  4],
       [ 1,  1,  1,  1,  1]])


### Given the X numpy matrix, change the last row with all 1

In [ ]:
# your code goes here
X[-1]=2
X

array([[ 2,  7, 10,  8,  7],
       [ 4,  8,  4,  1,  3],
       [ 9, -1, -1,  9, -1],
       [ 9, -1, 10,  1,  4],
       [ 2,  2,  2,  2,  2]])


### Given the X numpy matrix, change the last item on the last row with a 0

In [ ]:
# your code goes here
X[-1,-1]=0
X

array([[ 2,  7, 10,  8,  7],
       [ 4,  8,  4,  1,  3],
       [ 9, -1, -1,  9, -1],
       [ 9, -1, 10,  1,  4],
       [ 2,  2,  2,  2,  0]])


### Given the X numpy matrix, add 5 to every element

In [ ]:
# your code goes here
X+5

array([[ 7, 12, 15, 13, 12],
       [ 9, 13,  9,  6,  8],
       [14,  4,  4, 14,  4],
       [14,  4, 15,  6,  9],
       [ 7,  7,  7,  7,  5]])


## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [ ]:
# your code goes here

mask = X<0


mask

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False]])


### Given the X numpy array, get the negative elements

In [ ]:
# your code goes here
X[X<0]


array([-1, -1, -1, -1])


### Given the X numpy array, get numbers higher than 5

In [ ]:
# your code goes here
X[X>5]

array([ 7, 10,  8,  7,  8,  9,  9,  9, 10])


### Given the X numpy array, get numbers higher than the elements mean

In [ ]:
# your code goes here
X[X>X.mean()]

array([ 7, 10,  8,  7,  8,  9,  9,  9, 10])


### Given the X numpy array, get numbers equal to 2 or 10

In [ ]:
# your code goes here

X[(X==2) | (X==10)]

array([ 2, 10, 10,  2,  2,  2,  2])


## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [ ]:
# your code goes here
X = np.array([1,2,3,4,0])


np.all(X!=0)

False


### Given the X numpy array, return True if any of its elements is zero

In [ ]:
# your code goes here
np.any(X==0)

True


## Summary statistics

### Given the X numpy array, show the sum of its elements

In [ ]:
# your code goes here
X.sum()

10


### Given the X numpy array, show the mean value of its elements

In [ ]:
# your code goes here
X.mean()

2.0


### Given the X numpy matrix, show the sum of its columns

In [ ]:
# your code goes here
X = np.array([[ 2,  7, 10,  8,  7],
       [ 4,  8,  4,  1,  3],
       [ 9, -1, -1,  9, -1],
       [ 9, -1, 10,  1,  4],
       [ 1,  1,  1,  1,  1]])


X.sum(axis=0)

array([25, 14, 24, 20, 14])


### Given the X numpy matrix, show the mean value of its rows

In [ ]:
# your code goes here
X.mean(axis=1)

array([6.8, 4. , 3. , 4.6, 1. ])

### Given the X numpy array, show the max value of its elements

In [ ]:
# your code goes here
X.max()

NameError: ignored